### ISSUE TITLE
Build failing in Node 7.x

### ISSUE THREAD

**Issue by julien-c** [GoogleCloudPlatform/google-cloud-node#1753]
``` bash
$ npm install --save @google-cloud/vision

> grpc@1.0.0 install /Users/gibbon/devel/Katia-api/node_modules/grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.0/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.0 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp) 

```

And then when trying to compile:

```
  CC(target) Release/obj.target/grpc/src/core/lib/surface/init.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_args.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_stack.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_stack_builder.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/compress_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/connected_channel.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/http_client_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/http_server_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/compression/compression.o
  CC(target) Release/obj.target/grpc/src/core/lib/compression/message_compress.o
  CC(target) Release/obj.target/grpc/src/core/lib/debug/trace.o
  CC(target) Release/obj.target/grpc/src/core/lib/http/format_request.o
  CC(target) Release/obj.target/grpc/src/core/lib/http/httpcli.o
  CC(target) Release/obj.target/grpc/src/core/lib/http/parser.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/closure.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/endpoint.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/endpoint_pair_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/endpoint_pair_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/error.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/ev_epoll_linux.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/ev_poll_and_epoll_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/ev_poll_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/ev_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/exec_ctx.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/executor.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/iocp_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/iomgr.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/iomgr_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/iomgr_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/load_file.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/network_status_tracker.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/polling_entity.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/pollset_set_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/pollset_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/resolve_address_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/resolve_address_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/sockaddr_utils.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/socket_utils_common_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/socket_utils_linux.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/socket_utils_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/socket_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_client_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_client_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_server_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_server_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/time_averaged_stats.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/timer.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/timer_heap.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/udp_server.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/unix_sockets_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/unix_sockets_posix_noop.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/wakeup_fd_eventfd.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/wakeup_fd_nospecial.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/wakeup_fd_pipe.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/wakeup_fd_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/workqueue_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/workqueue_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/json/json.o
  CC(target) Release/obj.target/grpc/src/core/lib/json/json_reader.o
  CC(target) Release/obj.target/grpc/src/core/lib/json/json_string.o
  CC(target) Release/obj.target/grpc/src/core/lib/json/json_writer.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/alarm.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/api_trace.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/byte_buffer.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/byte_buffer_reader.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/call.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/call_details.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/call_log_batch.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/channel.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/channel_init.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/channel_ping.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/channel_stack_type.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/completion_queue.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/event_string.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/lame_client.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/metadata_array.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/server.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/validate_metadata.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/version.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/byte_stream.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/connectivity_state.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/metadata.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/metadata_batch.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/static_metadata.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/transport.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/transport_op_string.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/bin_decoder.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/bin_encoder.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/chttp2_plugin.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_data.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_goaway.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_ping.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_rst_stream.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_settings.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_window_update.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/hpack_encoder.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/hpack_parser.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/hpack_table.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/huffsyms.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/incoming_metadata.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/parsing.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/status_conversion.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/stream_lists.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/stream_map.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/timeout_encoding.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/varint.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/writing.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/alpn/alpn.o
  CC(target) Release/obj.target/grpc/src/core/lib/http/httpcli_security_connector.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/context/security_context.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/composite/composite_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/credentials_metadata.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/fake/fake_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/google_default/credentials_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/google_default/credentials_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/google_default/google_default_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/iam/iam_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/jwt/json_token.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/jwt/jwt_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/jwt/jwt_verifier.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/oauth2/oauth2_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/plugin/plugin_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/ssl/ssl_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/client_auth_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/handshake.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/secure_endpoint.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/security_connector.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/server_auth_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/tsi_error.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/util/b64.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/util/json_util.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/init_secure.o
  CC(target) Release/obj.target/grpc/src/core/lib/tsi/fake_transport_security.o
  CC(target) Release/obj.target/grpc/src/core/lib/tsi/ssl_transport_security.o
  CC(target) Release/obj.target/grpc/src/core/lib/tsi/transport_security.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/client/secure/secure_channel_create.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/channel_connectivity.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/client_channel.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/client_channel_factory.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/client_config.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/client_config_plugin.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/connector.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/default_initial_connect_string.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/initial_connect_string.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/lb_policy.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/lb_policy_factory.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/lb_policy_registry.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/parse_address.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/resolver.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/resolver_factory.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/resolver_registry.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/subchannel.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/subchannel_call_holder.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/subchannel_index.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/uri_parser.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.o
  CC(target) Release/obj.target/grpc/src/core/ext/lb_policy/grpclb/load_balancer_api.o
  CC(target) Release/obj.target/grpc/src/core/ext/lb_policy/grpclb/proto/grpc/lb/v1/load_balancer.pb.o
  CC(target) Release/obj.target/grpc/third_party/nanopb/pb_common.o
  CC(target) Release/obj.target/grpc/third_party/nanopb/pb_decode.o
  CC(target) Release/obj.target/grpc/third_party/nanopb/pb_encode.o
  CC(target) Release/obj.target/grpc/src/core/ext/lb_policy/pick_first/pick_first.o
  CC(target) Release/obj.target/grpc/src/core/ext/lb_policy/round_robin/round_robin.o
  CC(target) Release/obj.target/grpc/src/core/ext/resolver/dns/native/dns_resolver.o
  CC(target) Release/obj.target/grpc/src/core/ext/resolver/sockaddr/sockaddr_resolver.o
  CC(target) Release/obj.target/grpc/src/core/ext/load_reporting/load_reporting.o
  CC(target) Release/obj.target/grpc/src/core/ext/load_reporting/load_reporting_filter.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/context.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/gen/census.pb.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/grpc_context.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/grpc_filter.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/grpc_plugin.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/initialize.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/mlog.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/operation.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/placeholders.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/tracing.o
  CC(target) Release/obj.target/grpc/src/core/plugin_registry/grpc_plugin_registry.o
  LIBTOOL-STATIC Release/libgrpc.a
  CC(target) Release/obj.target/gpr/src/core/lib/profiling/basic_timers.o
  CC(target) Release/obj.target/gpr/src/core/lib/profiling/stap_timers.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/alloc.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/avl.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/backoff.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cmdline.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cpu_iphone.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cpu_linux.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cpu_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cpu_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/env_linux.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/env_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/env_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/histogram.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/host_port.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log_android.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log_linux.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/murmur_hash.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/slice.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/slice_buffer.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/stack_lockfree.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/string.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/string_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/string_util_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/string_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/subprocess_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/subprocess_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/sync.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/sync_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/sync_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/thd.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/thd_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/thd_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/time.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/time_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/time_precise.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/time_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/tls_pthread.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/tmpfile_msys.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/tmpfile_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/tmpfile_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/wrap_memcpy.o
  LIBTOOL-STATIC Release/libgpr.a
  CXX(target) Release/obj.target/grpc_node/src/node/ext/byte_buffer.o
../src/node/ext/byte_buffer.cc:99:49: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> fastBuffer = bufferConstructor->NewInstance(3, consArgs);
                                                ^
/Users/gibbon/.node-gyp/7.0.0/include/node/v8.h:3288:31: note: 'NewInstance' has been explicitly marked
      deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
1 warning generated.
  CXX(target) Release/obj.target/grpc_node/src/node/ext/call.o
../src/node/ext/call.cc:616:20: error: no member named 'SetHiddenValue' in 'v8::Object'
      info.This()->SetHiddenValue(Nan::New("channel_").ToLocalChecked(),
      ~~~~~~~~~~~  ^
../src/node/ext/call.cc:624:69: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    MaybeLocal<Object> maybe_instance = constructor->GetFunction()->NewInstance(
                                                                    ^
/Users/gibbon/.node-gyp/7.0.0/include/node/v8.h:3288:31: note: 'NewInstance' has been explicitly marked
      deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
1 warning and 1 error generated.
make: *** [Release/obj.target/grpc_node/src/node/ext/call.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/gibbon/devel/Katia-api/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/gibbon/devel/Katia-api/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /Users/gibbon/devel/Katia-api/node_modules/grpc
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/gibbon/devel/Katia-api/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/Users/gibbon/devel/Katia-api/node_modules/grpc/src/node/extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/gibbon/devel/Katia-api/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.0.0/bin/node" "/Users/gibbon/devel/Katia-api/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/gibbon/devel/Katia-api/node_modules/grpc
node-pre-gyp ERR! node -v v7.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/gibbon/devel/Katia-api/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/Users/gibbon/devel/Katia-api/node_modules/grpc/src/node/extension_binary' (1)
katia-api@1.0.0 /Users/gibbon/devel/Katia-api
└── @google-cloud/common@0.7.1  extraneous

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install" "--save" "@google-cloud/vision"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gibbon/devel/Katia-api/npm-debug.log
```

**Comment by stephenplusplus** [comment]
This issue was moved to grpc/grpc#8512

**Comment by stephenplusplus** [comment]
Sounds like a fix has been made and will be released upstream soon. After that, we'll update accordingly here. Thanks for reporting!

**Comment by randunel** [comment]
Build also fails on linux. Perhaps the title should be updated.

**Comment by stephenplusplus** [comment]
`grpc` has released a fix for this in 1.0.1. This will be resolved when we release our next version of `google-cloud`. For now, using modules directly will work for Node v7, e.g. `npm install --save @google-cloud/bigtable`.

**Comment by SimenB** [comment]
This fails for us as well, and our dep is `@google-cloud/storage`.

https://travis-ci.org/finn-no/cdn-uploader/builds/173181378

Any timeline for a release?

**Comment by stephenplusplus** [comment]
@SimenB that seems to be a different issue, see [this line](https://travis-ci.org/finn-no/cdn-uploader/jobs/173181379#L150):

> Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.

**Comment by samkelleher** [comment]
Also unable to run `@google-cloud/storage`, using circle-ci building on ubuntu-14 (_Trusty_ gcc version 4.8.4) using node 7.1:

If the upstream grpc depdency has been updated, suggest making a release for that vs waiting for the next feature release of google-cloud.

See log output below.

```
2016-11-09T15:15:43.906237454Z module.js:600
2016-11-09T15:15:43.906286334Z   return process.dlopen(module, path._makeLong(filename));
2016-11-09T15:15:43.906292167Z                  ^
2016-11-09T15:15:43.906350362Z 
2016-11-09T15:15:43.906364294Z Error: Error relocating /usr/src/app/node_modules/grpc/src/node/extension_binary/grpc_node.node: __fprintf_chk: symbol not found
2016-11-09T15:15:43.906368697Z     at Object.Module._extensions..node (module.js:600:18)
2016-11-09T15:15:43.906372606Z     at Module.load (module.js:490:32)
2016-11-09T15:15:43.906399561Z     at tryModuleLoad (module.js:449:12)
2016-11-09T15:15:43.906403729Z     at Function.Module._load (module.js:441:3)
2016-11-09T15:15:43.906407381Z     at Module.require (module.js:500:17)
2016-11-09T15:15:43.906411094Z     at require (internal/module.js:20:19)
2016-11-09T15:15:43.906414881Z     at Object.<anonymous> (/usr/src/app/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
2016-11-09T15:15:43.906419637Z     at Module._compile (module.js:573:32)
2016-11-09T15:15:43.906423322Z     at Object.Module._extensions..js (module.js:582:10)
2016-11-09T15:15:43.906427047Z     at Module.load (module.js:490:32)
2016-11-09T15:15:43.906430691Z     at tryModuleLoad (module.js:449:12)
2016-11-09T15:15:43.906434157Z     at Function.Module._load (module.js:441:3)
2016-11-09T15:15:43.906437781Z     at Module.require (module.js:500:17)
2016-11-09T15:15:43.906441292Z     at require (internal/module.js:20:19)
2016-11-09T15:15:43.906444709Z     at Object.<anonymous> (/usr/src/app/node_modules/grpc/src/node/src/client.js:55:12)
2016-11-09T15:15:43.906448487Z     at Module._compile (module.js:573:32)
2016-11-09T15:15:43.906451927Z     at Object.Module._extensions..js (module.js:582:10)
2016-11-09T15:15:43.906457082Z     at Module.load (module.js:490:32)
2016-11-09T15:15:43.906460581Z     at tryModuleLoad (module.js:449:12)
2016-11-09T15:15:43.906464056Z     at Function.Module._load (module.js:441:3)
2016-11-09T15:15:43.906467586Z     at Module.require (module.js:500:17)
2016-11-09T15:15:43.906503688Z     at require (internal/module.js:20:19)
```

**Comment by stephenplusplus** [comment]
I think that could be a matter of needing to rebuild the naive dependency. Can you try 'rm -rf node_modules && npm install'?

**Comment by samkelleher** [comment]
Trying with a blank env without cache was the first thing I tried. I also manually installed grpc 1.0.1 but this didn't actually help, so perhaps their fix hasn't resolved the issue as planned.

If I just downgrade to Node 6.9 everything works again with no other changes.  Will sit it out for a while. 👍🏻

**Comment by julien-c** [comment]
Same here

**Comment by adambuczynski** [comment]
Still failing against Node 7.1.0. Will remove google-cloud dependency until fixed, as we need to run on Node 7 to leverage some ES6 features.

**Comment by bjwatson** [comment]
@adambuczynski @julien-c @samkelleher @SimenB @randunel We are preparing a release to fix this issue today. @stephenplusplus will provide more details.

**Comment by stephenplusplus** [comment]
We've released 0.44.0 which hardcodes (via shrinkwrap) grpc@1.0.1. Thanks for your patience, everyone!

**Comment by SimenB** [comment]
@stephenplusplus Will there be precompiled versions of grpc made available for node@7?

**Comment by stephenplusplus** [comment]
We shrinkwrap to keep the size of the module down for npm < 3 users, by forcing a flatter dependency tree.

For any gRPC questions / issues, please direct them to their repo https://github.com/grpc/grpc

**Comment by bmustata** [comment]
Similar issue in here and we are considering dropping google-cloud.

**Comment by bjwatson** [comment]
@bmustata Are you saying that you're seeing exactly the same bug as described in this issue using the latest version of `google-cloud`?

FYI @jmuk.

**Comment by jmuk** [comment]
@murgatroid99 is in charge. Especially for the usage of Node7, https://github.com/grpc/grpc/issues/9311#issuecomment-275229720 said that:

> We have now released a new version. You should now be able to use grpc@1.1.0-pre1 with Windows and Node 7.

(I believe that this is not only for Windows but also for any platforms)

This would resolve the reported problems mostly. I am, however, wondering if we should wait for the actual 1.0.0 release for google-cloud packages, or we should quickly switch to this "pre1" version now.

Any ideas?

**Comment by murgatroid99** [comment]
Yes, that is for all platforms. We expect to have the actual 1.1.0 release published this week, so I would recommend changing your dependency to that version at that time.

**Comment by gilgil28** [comment]
any news?

**Comment by murgatroid99** [comment]
We have published grpc@1.1.0, which includes Node 7 support

**Comment by gilgil28** [comment]
I installed grpc@1.1.0, installation of google-cloud still fails

**Comment by bmustata** [comment]
Should we consider there is **not support** for **windows**? Good job google-cloud!

**Comment by jmuk** [comment]
There comes grpc@1.1.1 which should solve serious known issues and be distributed with pre-built binaries on platforms including Windows.

We should upgrade the current dependency to this -- otherwise the installation process will keep failing when a package dependency needs to install grpc@1.0.x.

**Comment by stephenplusplus** [comment]
`google-cloud@0.46.0` and all sub-submodules released with grpc 1.1.1. Please give it a shot!

**Comment by bjwatson** [comment]
Thanks @stephenplusplus!

**Comment by gilgil28** [comment]
I can confirm it now works!

**Comment by ksparakis** [comment]
For anyone that runs into this issue like I did, make sure to update your node if possible. I was running v0.12.0 of Node and after updating to v7.9.0 I was able to install the grpc package properly, which was stumping the google-cloud package.
