### ISSUE TITLE
data integrity validation fails in container w/ node 7.10

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/google-cloud-node#2373]
#### Environment details

  - OS: alpine *(official `node:7.10.0-alpine` image)*
  - Node.js version: 7.10
  - npm version: n/a
  - google-cloud-node version: 1.1.1

#### Steps to reproduce

  1. require `google-cloud`
  2. upload a file (from both API or console) and then `await file.download()`

N.B.

```js
const bucket = storage.bucket('something')
const file = bucket.file('aaaaa.json')
const content = await file.download({ validation: 'crc32' }) // or false
```

Will correctly download the file.

--- edit ---

The correct string is `crc32c` not `crc32`. The above example fails with `crc32c` and according to the documentation that's the default validation method.

**Comment by stephenplusplus** [comment]
I haven't been able to reproduce this with the same versions, but Windows. Can you be sure to clear out the node_modules directory and do a full re-install of all dependencies? This may be related to a problem that was fixed recently in a sub-dependency.

**Comment by kilianc** [comment]
@stephenplusplus I did try a fresh install with yarn and this is the tree:

```
"@google-cloud/storage@^1.1.1":
  version "1.1.1"
  resolved "https://registry.yarnpkg.com/@google-cloud/storage/-/storage-1.1.1.tgz#6590b5ce6e779556c9cc7043bd6449d6bc0781de"
  dependencies:
    "@google-cloud/common" "^0.13.0"
    arrify "^1.0.0"
    async "^2.0.1"
    concat-stream "^1.5.0"
    create-error-class "^3.0.2"
    duplexify "^3.2.0"
    extend "^3.0.0"
    gcs-resumable-upload "^0.7.1"
    hash-stream-validation "^0.2.1"
    is "^3.0.1"
    mime-types "^2.0.8"
    once "^1.3.1"
    pumpify "^1.3.3"
    stream-events "^1.0.1"
    string-format-obj "^1.0.0"
    through2 "^2.0.0"
```

Still no luck. Should I push an image with a failing case?

**Comment by kilianc** [comment]
@stephenplusplus also I just edited the post the base image is: `node:7.10-alpine`

**Comment by stephenplusplus** [comment]
>  Should I push an image with a failing case?

That would be great. I have tried again inside a Docker container, using that base image, and it succeeds.

**Comment by stephenplusplus** [comment]
@kilianc I'm going to close, as I can't reproduce. Let me know if there's more I can do to see what you're seeing, and I will happily re-open and continue the investigation.
